/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MainApp */

#ifndef _Included_MainApp
#define _Included_MainApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MainApp
 * Method:    setRotation
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_MainApp_setRotation
  (JNIEnv *, jobject, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
